site_name: Swingy Bone Physics Addon
theme:
  name: material
  custom_dir: custom
  features:
    - navigation.expand
    - navigation.path
    - search.suggest
    - navigation.sections
    - navigation.top
  logo: Resources/Images/Logo.png  
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  language: en
  palette:    
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
      primary: indigo
      accent: purple 
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode    
      primary: indigo
      accent: purple 
nav:
  - Overview: 'index.md'
  - Addon Setup: 'setup.md'
  - Quickstart: 'quickstart.md'  
  - Bone chain: 
    - Getting started: 'bone-chain/basics.md'
    - Operators: 'bone-chain/operators.md'
    - Parameters: 'bone-chain/parameters.md'
    - Amplitude limit: 'bone-chain/amplitude.md'
    - Wind: 'bone-chain/wind.md'
  - Colliders: 
    - Getting started: 'collider/basics.md'
    - Operators: 'collider/operators.md'
    - Parameters: 'collider/parameters.md'
  - Curves:
    - Getting started: 'curve/basics.md'
    - Parameter curves: 'curve/parameter.md'
    - Wind curves: 'curve/wind.md'
  - Misc:
    - Performance tips: 'performance.md'
    - Changelog: 'changelog.md'
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
plugins:
  - glightbox
  - search

